"""make_hashed_password_nullable

Revision ID: 40d126059597
Revises: 4c2304d93ded
Create Date: 2026-04-24 19:46:17.154528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40d126059597'
down_revision: Union[str, None] = '4c2304d93ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
